config/routes.rb
Rails.application.routes.draw do

  post 'products/delete'
  get 'products/check'
  post 'products/regist'
  post 'products/upload'
  get 'products/show'
  post 'products/search'
  post 'products/set_csv'
  get 'products/setup'
  post 'products/setup'
  get 'products/prepare'
  post 'products/prepare'
  root to: 'products#show'

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/sign_in' => 'devise/sessions#new'
  end

  devise_for :users, :controllers => {
   :registrations => 'users/registrations'
  }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  require 'open-uri'
  require 'peddler'
  require 'uri'
  require 'net/http'

  before_action :authenticate_user!, :except => [:regist, :check, :delete]
  protect_from_forgery :except => [:regist, :check, :delete]

  def delete
    if request.post? then
      logger.debug("====== delete Start =======")
      user = params[:user]
      password = params[:password]
      tuser =  User.find_by(email: user)
      if tuser != nil then
        #delete
        if tuser.valid_password?(params[:password]) then
          tuser.delete
          logger.debug("user delete")
        end
      end
    end
  end

  def show
    @login_user = current_user
  end

  def search
    if request.post? then
      request = params[:data]
      request = JSON.parse(request)
      data = request[0]
      counter = request[1]

      logger.debug("========================")
      logger.debug("No. " + counter.to_s)
      logger.debug(data)
      result = Array.new
      data.each_with_index do |row, index|
        logger.debug("+++++++++++++++++++++++++++++++++")
        logger.debug(row)
        buf = nil
        url = row[0]
        if url != nil && url != '' then
          buf = Array.new
          if url.include?("auctions.yahoo") then
            logger.debug("====== Yahoo Auction =======")
            
            auctionID = url.gsub("https://page.auctions.yahoo.co.jp/jp/auction/", "")

            uri = URI.parse(url)
            http = Net::HTTP.new(uri.host, uri.port)
            http.use_ssl = uri.scheme === "https"
            # http.set_debug_output($stderr)

            headers = {
              "User-Agent" => "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36",
              "Connection" => "keep-alive",
            }

            response = http.get(uri.path, headers)
            html = response.body
=begin
            charset = nil
            option = {
              "User-Agent" => "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36",
              "Connection" => "keep-alive",
              "Accept" => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3'
            }
            html = open(url, option) do |f|
              charset = f.charset # 文字種別を取得
              f.read # htmlを読み込んで変数htmlに渡す
            end
=end
            charset = "UTF-8"
            html = html.force_encoding("UTF-8")
            doc = Nokogiri::HTML.parse(html)
            if doc.xpath('//p[@class="ptsFin"]')[0] == nil then
              #商品が出品中の場合
              title = doc.xpath('//h1[@class="ProductTitle__text"]')[0].text.gsub("\n","")
              productinfo = doc.xpath('//li[@class="ProductDetail__item"]')
              condition = /<th class="ProductTable__th">状態<\/th>([\s\S]*?)\/li>/.match(html)
              if condition != nil then
                condition = condition[1]
                condition = /<li class="ProductTable__item">([\s\S]*?)\/a>/.match(condition)
                if condition.present? then                  
                  condition = condition[1]
                  if condition.include?(">") then 
                    logger.debug("------ condition -------")
                    logger.debug(condition)
                    condition = />([\s\S]*?)</.match(condition)[1]
                    logger.debug("------------")
                    logger.debug(condition)
                  end
                  condition = condition.gsub(/\R/, "")
                  condition = condition.strip
                end
                logger.debug(condition)
              else 
                condition = ""
              end
              k = 0
              while k < productinfo.length
                str = productinfo[k].text
                if str.include?("オークションID") == true then
                  auctionID = productinfo[k].inner_html.match(/pan>([\s\S]*?)<\/dd/)[1]
                end
                k += 1
              end
              k = 0
               

              priceType = doc.xpath('//dd[@class="Price__value"]')
              if priceType[0] != nil then
                listPrice = priceType[0].text.gsub("\n","")
                if listPrice.include?("（税 0 円）") == true then
                  listPrice = listPrice.gsub(/（税 0 円）/,"")
                  listPrice = CCur(listPrice)
                else
                  listPrice = listPrice.match(/税込([\s\S]*?)円/)[1]
                  listPrice = CCur(listPrice)
                end
              else
                listPrice = 0
              end

              priceType = doc.xpath('//dd[@class="Price__value Price__value--buyNow"]')
              if priceType[0] != nil then
                binPrice = priceType[0].text.gsub("\n","")
                if binPrice.include?("（税 0 円）") == true then
                  binPrice = binPrice.gsub(/（税 0 円）/,"")
                  binPrice = CCur(binPrice)
                else
                  binPrice = binPrice.match(/税込([\s\S]*?)円/)[0]
                  binPrice = binPrice.gsub(/税込/,"")
                  binPrice = CCur(binPrice)
                end
              else
                binPrice = 0
              end

              #bitnum = doc.xpath('//dd[@class="Count__number"]')[0].text
              #bitnum = bitnum.slice(0,bitnum.length-4)
              #bitnum = doc.xpath('//span[@class="Count__detail"]')[0].text
              #bitnum = bitnum.gsub("件", "")
              bitnum = ""
                
              #restTime = doc.xpath('//dd[@class="Count__number"]')[1].text
              #restTime = restTime.slice(0,restTime.length-4)
              restTime = ""
              images = doc.xpath('//div[@class="ProductImage__inner"]')
              image = []

              k = 0

              while k < images.length
                str = images[k].inner_html
                image[k] = str.match(/src="([\s\S]*?)"/)[1]
                k += 1
              end
              logger.debug("-------")
              seller_id = doc.xpath('//span[@class="Seller__name"]/a/text()').text

              logger.debug(seller_id)

            else
              #オークションが終了している場合
              logger.debug("======END ACUTION======")
              title = doc.xpath('//h1[@property="auction:Title"]')[0].text
              title = "[終了したオークション]" + title

              auctionID = doc.xpath('//td[@property="auction:AuctionID"]')[0]
              if auctionID != nil then
                auctionID = auctionID.text
              end
              condition = doc.xpath('//td[@property="auction:ItemStatus"]')[0]
              if condition != nil then
                condition = condition.text
                condition = condition.gsub(/\R/, "")
                condition = condition.strip
              end

              binPrice = ""
              checkTax = doc.xpath('//p[@class="decTxtTaxIncPrice"]')[0]
              if checkTax != nil then
                checkTax = checkTax.text
              end

              logger.debug(url)

              listPrice = doc.xpath('//p[@class="decTxtBuyPrice Price__value"]')[0]
              if listPrice != nil then
                listPrice = doc.xpath('//p[@class="decTxtBuyPrice Price__value"]')[0].text
              else
                listPrice = doc.xpath('//p[@class="decTxtAucPrice Price__value"]')[0].text
              end
              listPrice = CCur(listPrice)
              if listPrice != nil then
                if listPrice.include?("%") then
                  listPrice = /^([\s\S]*?)\s/.match(listPrice)[1]
                end
              end
              binPrice = 0
              bitnum = doc.xpath('//b[@property="auction:Bids"]')[0]
              if bitnum != nil then
                bitnum = bitnum.text
              end

              restTime = "終了"
              k = 0
              image = []
              while k < 3
                images = doc.xpath('//img[@id="imgsrc' + (k+1).to_s + '"]')
                if images[0] != nil then
                  image[k] = images[0].attribute("src").value
                end
                k += 1
              end
              logger.debug("---end----")
              seller_id =/出品者<\/th>([\s\S]*?)<\/a>/.match(html)[1]
              logger.debug("---end2----")
              logger.debug(seller_id)
              seller_id =/" >([\s\S]*?)$/.match(seller_id)[1]
              logger.debug(seller_id)
            end

            title = title.gsub("\t", "")

            if image[0] != nil then
              im = '<img src="' + image[0].to_s  + '" style="height: 50px; margin:auto" >'
            else
              im = ''
            end

            buf = [url, im, title, auctionID, listPrice, binPrice, condition, bitnum, restTime]
            (0..7).each do |int|
              if image[int] != nil then
                buf.push(image[int])
              else
                buf.push("")
              end
            end
            buf.push(seller_id)

          elsif url.include?("otamart") then
            logger.debug("====== Otamart =======")

            if url[-1] != "/" then
              url = url + "/"
            end
            logger.debug(url)
            option = {
              "User-Agent" => "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36",
              "Connection" => "keep-alive",
              "Accept" => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3'
            }
            html = open(url, option) do |f|
              charset = f.charset # 文字種別を取得
              f.read # htmlを読み込んで変数htmlに渡す
            end

            title = /"name": "([\s\S]*?)"/.match(html)[1]
            if html.include?("売り切れました") then

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/prepare.html.erb
<div class="container">
  <div class="page-header" id="banner">
    <div class="row my-4">
      <div class="col-12">
      <h2>ツールの各種設定</h2>
      </div>
      <div class="col-6">
        <hr class="my-4">
        <h4>MWSアカウントの設定</h4>
        <%= form_for(@account, {url: products_prepare_path, method: 'post'}) do |f| %>
          <div class="form-group">
            <%= f.label :seller_id, "セラーID" %>
            <%= f.text_field :seller_id, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :aws_access_key_id, "AWSアクセスキー" %>
            <%= f.text_field :aws_access_key_id, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :secret_key, "秘密キー" %>
            <%= f.text_field :secret_key, class: 'form-control' %>
          </div>
          <%= f.submit "設定する", {id: "setup_btn", class: 'btn btn-primary'} %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products/setup.html.erb
<div class="container">
  <div class="page-header" id="banner">
    <div class="row my-4">
      <div class="col-lg-12">
        <div class="form-inline">
        <h2>ツールの各種設定</h2><button id="setup_data" class="btn btn-primary" style="margin-left:30px; margin-bottom:10px;">設定を反映する</button>
        </div>
      </div>
      <div class="col-lg-8">
        <hr class="my-4">
        <h4>定型パラメータの設定</h4>
        <div id="fix_table"></div>
      </div>
      <div class="col-lg-4">
        <hr class="my-4">
        <h4>除外セラーの設定</h4>
        <div id="ng_seller_table"></div>
      </div>
      <div class="col-lg-12">
        <hr class="my-4">
        <h4>キーワードとの紐づけ設定</h4>
        <div id="keyword_table"></div>
      </div>

      <div class="col-lg-6">
        <hr class="my-4">
        <h4>販売価格テーブルの設定</h4>
        <div id="price_table"></div>
      </div>
      <div class="col-lg-6">
        <hr class="my-4">
        <h4>商品名置換テーブルの設定</h4>
        <div id="replace_table"></div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  var maxColnum = 2;
  var maxRownum = 500;

  var pdata = <%= @pdata %>;
  var fdata = <%= @fdata %>;
  var tdata = <%= @tdata %>;
  var kdata = <%= @kdata %>;
  var ndata = <%= @ndata %>;

  if(pdata.length == 0){
    var pdata = [];
    var rnum = 100;
    for(var i = 0; i < rnum; i++){
      pdata[i] = [];
      pdata[i][0] = i * 5000;
      pdata[i][1] = i * 5000 + 2980;
    }
  }else{
    var rnum = 100;
    for(var i = pdata.length; i < rnum; i++){
      pdata[i] = [];
      pdata[i][0] = "";
      pdata[i][1] = "";
    }
  }

  if(fdata.length == 0){
    var rnum = 10;
    for(var i = 0; i < rnum; i++){
      fdata[i] = [];
      fdata[i][0] = "";
      fdata[i][1] = "";
      fdata[i][2] = "";
    }

    fdata[0][0] = "feed_product_type"
    fdata[1][0] = "quantity"
    fdata[2][0] = "recommended_browse_nodes"
    fdata[3][0] = "fulfillment_latency"
    fdata[4][0] = "condition_type"
    fdata[5][0] = "condition_note"
    fdata[6][0] = "standard_price_points"
    fdata[0][1] = "商品タイプ"
    fdata[1][1] = "数量"
    fdata[2][1] = "推奨ブラウズノード番号"
    fdata[3][1] = "出荷作業日数"
    fdata[4][1] = "商品のコンディション"
    fdata[5][1] = "商品のコンディション説明"
    fdata[6][1] = "ポイント（販売価格に対するパーセントを記入）"
  }else{
    var rnum = 10;
    for(var i = fdata.length; i < rnum; i++){
      fdata[i] = [];
      fdata[i][0] = "";
      fdata[i][1] = "";
      fdata[i][2] = "";
    }
  }


  var price_container = document.getElementById('price_table');
  var price_handsontable = Handsontable(price_container, {
    /* オプション */
    width: '100%',
    height: 240,
    data: pdata,
    contextMenu: true,
    rowHeaders: true,
    colHeaders: ["ヤフオク販売価格","アマゾン販売価格"],
    maxCols: maxColnum,
    maxRows: maxRownum,
    manualColumnResize: true,
    autoColumnSize: false,
    colWidths:[200, 200]
  });
  console.log("-------------");
  console.log(fdata);
  var fix_container = document.getElementById('fix_table');
  var fix_handsontable = Handsontable(fix_container, {
    /* オプション */
    width: '100%',
    height: 240,
    data: fdata,
    contextMenu: true,
    rowHeaders: true,
    colHeaders: ["項目名","説明","値"],
    maxCols: 3,
    maxRows: maxRownum,
    manualColumnResize: true,
    autoColumnSize: false,
    colWidths:[200, 220, 230]
  });


  var mnum = 3000;
  if(tdata.length == 0){
    for(var i = 0; i < mnum; i++){
      tdata[i] = [];
      tdata[i][0] = "";
      tdata[i][1] = "";
    }
  }else{
    for(var i = tdata.length; i < mnum; i++){
      tdata[i] = [];
      tdata[i][0] = "";
      tdata[i][1] = "";
    }
  }

  var title_container = document.getElementById('replace_table');
  var title_handsontable = Handsontable(title_container, {
    /* オプション */
    width: '100%',
    height: 240,
    data: tdata,
    contextMenu: true,
    rowHeaders: true,
    colHeaders: ["置換前","置換後"],
    maxCols: maxColnum,
    maxRows: mnum,
    manualColumnResize: true,
    autoColumnSize: false,
    colWidths:[200, 200]
  });

  var mnum = 500;
  if(kdata.length == 0){
    for(var i = 0; i < mnum; i++){
      kdata[i] = [];
      kdata[i][0] = "";
      kdata[i][1] = "";
      kdata[i][2] = "";
      kdata[i][3] = "";
      kdata[i][4] = "";
    }
  }else{
    for(var i = kdata.length; i < mnum; i++){
      kdata[i] = [];
      kdata[i][0] = "";
      kdata[i][1] = "";
      kdata[i][2] = "";
      kdata[i][3] = "";
      kdata[i][4] = "";
    }
  }

  var keyword_container = document.getElementById('keyword_table');
  var keyword_handsontable = Handsontable(keyword_container, {
    /* オプション */
    width: '100%',
    height: 240,
    data: kdata,
    contextMenu: true,
    rowHeaders: true,
    colHeaders: ["キーワード","brand_name（ブランド名）","manufacturer（メーカ名）","recommended_browse_nodes（推奨ブラウズノード）","generic_keywords（検索キーワード）"],
    maxCols: 5,
    maxRows: mnum,
    manualColumnResize: true,
    autoColumnSize: false,
    colWidths:[200, 250, 250, 450, 400]
  });


  var mnum = 3000;

  if(ndata.length == 0){
    for(var i = 0; i < mnum; i++){
      ndata[i] = [];
      ndata[i][0] = "";
    }
  }else{
    for(var i = ndata.length; i < mnum; i++){
      ndata[i] = [];
      ndata[i][0] = "";
    }
  }

  var ng_seller_container = document.getElementById('ng_seller_table');
  var ng_seller_handsontable = Handsontable(ng_seller_container, {
    /* オプション */
    width: '100%',
    height: 240,
    data: ndata,
    contextMenu: true,
    rowHeaders: true,
    colHeaders: ["除外セラーID"],
    maxCols: 1,
    maxRows: mnum,
    manualColumnResize: true,
    autoColumnSize: false,
    colWidths:[250]
  });

  $("#setup_data").click(function () {
    var pricedata = price_handsontable.getData();
    var titledata = title_handsontable.getData();
    var keydata = keyword_handsontable.getData();
    var fixdata = fix_handsontable.getData();
    var ngdata = ng_seller_handsontable.getData();

    var sdata = {price: pricedata, title: titledata, keyword: keydata, fixed: fixdata, ng: ngdata};
    sdata = JSON.stringify(sdata);
    send_data = {data: sdata};

    $.ajax({
      url: "/products/setup",
      type: "POST",
      data: send_data,
      dataType: 'json',
      success: function (myData) {
        alert("更新しました");
      },
      error: function (myData) {
        alert("更新しました");
      }
    });
  });

</script>

app/views/products/show.html.erb
<div class="container">
  <div class="page-header" id="banner">
    <div class="row my-4">
      <div class="col-12">
        <h2>Tmaster<small style="margin-left:20px;">アマゾン出品支援ツール</small></h2>
        <h4><strong>仕入れ先から情報取得</strong></h4>
        <button id="done" class="btn btn-primary" style="margin-right:20px;">情報取得開始</button>
        <button id="make_csv" class="btn btn-info" style="margin-right:20px;">出品データ作成</button>
        <% @tt = Time.now.strftime("_%Y%m%D%H%M%S") %>
        <a href="#" id="csv_output" download="アマゾン新規出品<%= @tt %>.txt" class="btn btn-primary" style="margin-right:20px;">ファイル出力</a>
        <button id="csv_upload" class="btn btn-info" style="margin-right:20px;">アップロード</button>
        <br>
        <div class="progress progress-striped active"  style="margin-top:20px; width:60%;">
          <div class="progress-bar" style="width: 0%" id="progressbar"></div>
        </div>
        <div id="main"></div>
        <br>
        <h4><strong>出品用ファイルの確認</strong></h4>
        <div id="selected"></div>
        <div id="csv"></div>
      </div>
    </div>
  </div>
</div>